//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfWirelessMedia.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WirelessMedia2018Entities : DbContext
    {
        public WirelessMedia2018Entities()
            : base("name=WirelessMedia2018Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljac> Dobavljac { get; set; }
        public virtual DbSet<Kategorija> Kategorija { get; set; }
        public virtual DbSet<Proizvodjac> Proizvodjac { get; set; }
        public virtual DbSet<Proizvod> Proizvod { get; set; }
    
        public virtual ObjectResult<SnimiProizvod_Result> SnimiProizvod(Nullable<int> idProizvodjac, Nullable<int> idDobavljac, Nullable<int> idKategorija, string naziv, string opis, Nullable<decimal> cena)
        {
            var idProizvodjacParameter = idProizvodjac.HasValue ?
                new ObjectParameter("IdProizvodjac", idProizvodjac) :
                new ObjectParameter("IdProizvodjac", typeof(int));
    
            var idDobavljacParameter = idDobavljac.HasValue ?
                new ObjectParameter("IdDobavljac", idDobavljac) :
                new ObjectParameter("IdDobavljac", typeof(int));
    
            var idKategorijaParameter = idKategorija.HasValue ?
                new ObjectParameter("IdKategorija", idKategorija) :
                new ObjectParameter("IdKategorija", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var opisParameter = opis != null ?
                new ObjectParameter("Opis", opis) :
                new ObjectParameter("Opis", typeof(string));
    
            var cenaParameter = cena.HasValue ?
                new ObjectParameter("Cena", cena) :
                new ObjectParameter("Cena", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SnimiProizvod_Result>("SnimiProizvod", idProizvodjacParameter, idDobavljacParameter, idKategorijaParameter, nazivParameter, opisParameter, cenaParameter);
        }
    
        public virtual ObjectResult<UpdateProizvoda_Result> UpdateProizvoda(Nullable<int> id, string nazivProizvoda, string opisProizvoda, Nullable<decimal> cenaProizvoda)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nazivProizvodaParameter = nazivProizvoda != null ?
                new ObjectParameter("NazivProizvoda", nazivProizvoda) :
                new ObjectParameter("NazivProizvoda", typeof(string));
    
            var opisProizvodaParameter = opisProizvoda != null ?
                new ObjectParameter("OpisProizvoda", opisProizvoda) :
                new ObjectParameter("OpisProizvoda", typeof(string));
    
            var cenaProizvodaParameter = cenaProizvoda.HasValue ?
                new ObjectParameter("CenaProizvoda", cenaProizvoda) :
                new ObjectParameter("CenaProizvoda", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UpdateProizvoda_Result>("UpdateProizvoda", idParameter, nazivProizvodaParameter, opisProizvodaParameter, cenaProizvodaParameter);
        }
    
        public virtual ObjectResult<VratiProizvode_Result> VratiProizvode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VratiProizvode_Result>("VratiProizvode");
        }
    
        public virtual ObjectResult<VratiProizvodPoId_Result> VratiProizvodPoId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VratiProizvodPoId_Result>("VratiProizvodPoId", idParameter);
        }
    }
}
